TODO
- Transition detection
- Novelty detection
- Visual output/dashboard

ISSUES
- Data collector is not generating database, Keeps giving 'corrupted' errors, unsure why



IDEA:
- Use a telemetry / vr capture to expand database of personal use, maybe find new features to use as input for the system

LATEST ERROR:

- Problem when the active labelling is complete. Next thing to fix:

127.0.0.1 - - [19/Jan/2024 15:04:23] "POST /label_input HTTP/1.1" 200 -
127.0.0.1 - - [19/Jan/2024 15:04:23] "GET /get_video_frame HTTP/1.1" 200 -
Put down
127.0.0.1 - - [19/Jan/2024 15:04:26] "POST /label_input HTTP/1.1" 200 -
c:\Users\jbdbo\Desktop\Q2 Research ML Design\[4] GUI\AI_for_Designers\active_learning.py:549: UserWarning:

Starting a Matplotlib GUI outside of the main thread will likely fail.

127.0.0.1 - - [19/Jan/2024 15:04:26] "GET /get_video_frame HTTP/1.1" 200 -
WARNING: QApplication was not created in the main() thread.
Exception in thread Thread-57 (run_active_learning):
Traceback (most recent call last):
  File "C:\Users\jbdbo\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\jbdbo\anaconda3\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\jbdbo\Desktop\Q2 Research ML Design\[4] GUI\interfacePrototpyeV2.py", line 51, in run_active_learning
    initiate_active_learning(product_name, frame_size, labels, iterations, label_input_queue)
  File "c:\Users\jbdbo\Desktop\Q2 Research ML Design\[4] GUI\machineLearningApp.py", line 78, in initiate_active_learning
    labels = AL.training(active_learning_iterations)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jbdbo\Desktop\Q2 Research ML Design\[4] GUI\AI_for_Designers\active_learning.py", line 141, in training
    self.iterate(maximum_iterations)
  File "c:\Users\jbdbo\Desktop\Q2 Research ML Design\[4] GUI\AI_for_Designers\active_learning.py", line 272, in iterate
    new_index, margin = self.set_ambiguous_point([iter_num, max_iter])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jbdbo\Desktop\Q2 Research ML Design\[4] GUI\AI_for_Designers\active_learning.py", line 296, in set_ambiguous_point
    self.print_prediction_point(get_id_to_label)
  File "c:\Users\jbdbo\Desktop\Q2 Research ML Design\[4] GUI\AI_for_Designers\active_learning.py", line 571, in print_prediction_point
    plt.savefig(f'Plots/plot_to_label_{self.html_id}.png')
  File "C:\Users\jbdbo\AppData\Roaming\Python\Python311\site-packages\matplotlib\pyplot.py", line 959, in savefig
    res = fig.savefig(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 * Detected change in 'C:\\Users\\jbdbo\\AppData\\Roaming\\Python\\Python311\\site-packages\\matplotlib\\pyplot.py', reloading
  File "C:\Users\jbdbo\AppData\Roaming\Python\Python311\site-packages\matplotlib\figure.py", line 3285, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "C:\Users\jbdbo\AppData\Roaming\Python\Python311\site-packages\matplotlib\backends\backend_qtagg.py", line 82, in print_figure
 * Detected change in 'C:\\Users\\jbdbo\\AppData\\Roaming\\Python\\Python311\\site-packages\\matplotlib\\figure.py', reloading
    super().print_figure(*args, **kwargs)
  File "C:\Users\jbdbo\AppData\Roaming\Python\Python311\site-packages\matplotlib\backend_bases.py", line 2338, in print_figure
 * Detected change in 'C:\\Users\\jbdbo\\AppData\\Roaming\\Python\\Python311\\site-packages\\matplotlib\\backends\\backend_qtagg.py', reloading
    result = print_method(
 * Detected change in 'C:\\Users\\jbdbo\\AppData\\Roaming\\Python\\Python311\\site-packages\\matplotlib\\backend_bases.py', reloading
             ^^^^^^^^^^^^^
  File "C:\Users\jbdbo\AppData\Roaming\Python\Python311\site-packages\matplotlib\backend_bases.py", line 2204, in <lambda>
    print_method = functools.wraps(meth)(lambda *args, **kwargs: meth(
                                                                 ^^^^^
  File "C:\Users\jbdbo\AppData\Roaming\Python\Python311\site-packages\matplotlib\_api\deprecation.py", line 410, in wrapper
    return func(*inner_args, **inner_kwargs)
 * Detected change in 'C:\\Users\\jbdbo\\AppData\\Roaming\\Python\\Python311\\site-packages\\matplotlib\\_api\\deprecation.py', reloading
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbdbo\AppData\Roaming\Python\Python311\site-packages\matplotlib\backends\backend_agg.py", line 517, in print_png
    self._print_pil(filename_or_obj, "png", pil_kwargs, metadata)
 * Detected change in 'C:\\Users\\jbdbo\\AppData\\Roaming\\Python\\Python311\\site-packages\\matplotlib\\backends\\backend_agg.py', reloading
  File "C:\Users\jbdbo\AppData\Roaming\Python\Python311\site-packages\matplotlib\backends\backend_agg.py", line 464, in _print_pil
    mpl.image.imsave(
  File "C:\Users\jbdbo\AppData\Roaming\Python\Python311\site-packages\matplotlib\image.py", line 1667, in imsave
    image.save(fname, **pil_kwargs)
  File "C:\Users\jbdbo\anaconda3\Lib\site-packages\PIL\Image.py", line 2428, in save
 * Detected change in 'C:\\Users\\jbdbo\\AppData\\Roaming\\Python\\Python311\\site-packages\\matplotlib\\image.py', reloading
    fp = builtins.open(filename, "w+b")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 * Detected change in 'C:\\Users\\jbdbo\\anaconda3\\Lib\\site-packages\\PIL\\Image.py', reloading
FileNotFoundError: [Errno 2] No such file or directory: 'Plots/plot_to_label_1705673066.4683943.png'
Exception in thread Thread-2 (serve_forever):
Traceback (most recent call last):
  File "C:\Users\jbdbo\anaconda3\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\jbdbo\anaconda3\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\jbdbo\anaconda3\Lib\site-packages\werkzeug\serving.py", line 766, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "C:\Users\jbdbo\anaconda3\Lib\socketserver.py", line 233, in serve_forever
    ready = selector.select(poll_interval)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbdbo\anaconda3\Lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jbdbo\anaconda3\Lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 10038] An operation was attempted on something that is not a socket